version: '3.9'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis_container

  reverse-proxy:
    image: wcs_file
    ports:
      - "80:80"
      - "6060:6060"
    container_name: wcs_container
    volumes:
      - ./wcs:/build/wcs
    environment:
      - KEY1=value1
      - KEY2=value2
    depends_on:
      - redis
