version: '3.9'
services:
  reverse-proxy:
    image: wcs
    ports:
      - "80:80"
    container_name: wcs_container
    volumes:
      - ./wcs:/build/wcs
    environment:
      - KEY1=value1
      - KEY2=value2
